# Generated by Django 5.1.5 on 2025-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling_number', models.BigIntegerField()),
                ('called_number', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
