# Generated by Django 5.1.5 on 2025-02-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('callback', models.IntegerField(blank=True, null=True)),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('userfield', models.CharField(max_length=255)),
                ('cnum', models.CharField(blank=True, max_length=80, null=True)),
                ('recordingfile', models.CharField(blank=True, max_length=255, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=80, null=True)),
                ('extra', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'cdr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=30)),
                ('eventtime', models.DateTimeField()),
                ('exten', models.CharField(max_length=80)),
                ('context', models.CharField(max_length=80)),
                ('channame', models.CharField(max_length=80)),
                ('appname', models.CharField(max_length=80)),
                ('appdata', models.CharField(max_length=80)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('peer', models.CharField(max_length=80)),
                ('userfield', models.CharField(max_length=255)),
                ('clid', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_num', models.CharField(blank=True, max_length=80, null=True)),
                ('linkedid', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_name', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_dani', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_dnid', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_rdnis', models.CharField(blank=True, max_length=80, null=True)),
                ('cid_ani', models.CharField(blank=True, max_length=80, null=True)),
                ('extra', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'cel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblServicenetNums',
            fields=[
                ('personid', models.AutoField(db_column='Personid', primary_key=True, serialize=False)),
                ('saxeli', models.CharField(max_length=200)),
                ('gvari', models.CharField(max_length=200)),
                ('piradi_nomeri', models.CharField(max_length=200)),
                ('kompania', models.CharField(max_length=200)),
                ('pozicia', models.CharField(max_length=200)),
                ('regioni', models.CharField(max_length=200)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_servicenet_nums',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UssdIvr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ussd', models.CharField(blank=True, db_column='USSD', max_length=255, null=True)),
                ('ivr', models.CharField(blank=True, db_column='IVR', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ussd_ivr',
                'managed': True,
            },
        ),
    ]
